### ISSUE TITLE
Nested objects type safe

### ISSUE THREAD

**Issue by nimahkh** [nimatrengo/soft_bun#24]
In the following example, 'user.age' will throw an error

```typescript
const initialState = {
        user: {
            name: "John Doe",
            age: 30,
            address: {
                street: "123 Main St",
                city: "Anytown",
                country: "USA"
            }
        },
        products: [
            { id: 1, name: "Product A", price: 10 },
            { id: 2, name: "Product B", price: 20 }
        ],
        total: 0
    };

    // Create a StateManager instance
    const largeStateManager = new StateManager(initialState);

    // Add reactive dependencies
    largeStateManager.reactive('user.age', '$user.age * 2');
```

Error: 'Argument of type '"user.age"' is not assignable to parameter of type '"user" | "products" | "total"'.'

**Comment by Mostafa-Mohammadi** [comment]
I was unable to reproduce the error after executing this code snippet in the playground. Everything appears to be functioning correctly, including the top-level total.

However, the underlying issue does not pertain to data typing. When I run this code, the age remains at 30, whereas it should have changed to 60. As I mentioned the top-level total property works fine.

Do you encounter a similar problem, or have I overlooked something in the configurations?

**Comment by nimahkh** [comment]
Well done Mostafa, 
I think it is related to another issue you already created: #25 
Let's fix it there

**Comment by nimahkh** [comment]
Related issue
https://github.com/nimahkh/soft_bun/issues/25
