### ISSUE TITLE
Nested Object

### ISSUE THREAD

**Issue by Mostafa-Mohammadi** [nimatrengo/soft_bun#25]
After revising various test cases, it has come to my attention that our current implementation does not support the addition of reactivity for nested objects.

For instance:

```javascript
const data = {a: 1, b: 2, c: {d: 2, e: 3}};
const state = new State(data);
state.reactive('c.d', '$c.e + $a');
expect(state.state.c.d).to.equal(4);
```

In this specific scenario, the property 'd' remains unchanged at a value of 2.

I would like to inquire whether there are any plans to address this issue. Alternatively, I am open to submitting a pull request to contribute to its resolution.

**Comment by nimahkh** [comment]
Good one Mostafa, I would appreciate if you could share your solution.

**Comment by nimahkh** [comment]
This issue has been solved
https://github.com/nimahkh/soft_bun/pull/27

**Comment by nimahkh** [comment]
The issue has been solved 
https://github.com/nimahkh/soft_bun/pull/27

soft_bun (1.7.4)
